[providers]
nodejs = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "ffmpeg"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"